package Main;
import java.security.SecureRandom;

import Model.DBConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.DriverManager;

import javax.swing.JSpinner;
import javax.swing.SpinnerNumberModel; // or other SpinnerModel if you're using one
import javax.swing.JFileChooser;
import java.io.File;
import javax.swing.filechooser.FileFilter;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.StandardCopyOption;
import javax.swing.JOptionPane;

import java.io.*;
import java.net.HttpURLConnection;
import java.net.URL;

import javax.swing.SwingWorker;
import javax.swing.JOptionPane;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Dilki Raveesha
 */

public class AddReportPage extends javax.swing.JFrame {
    private static final String CHARACTERS = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";
    private static final SecureRandom random = new SecureRandom();
    
private File selectedFile = null;
    /**
     * Creates new form AddReportPage
     */

 public static String generateShortHash(int length) {
        StringBuilder sb = new StringBuilder(length);
        for (int i = 0; i < length; i++) {
            sb.append(CHARACTERS.charAt(random.nextInt(CHARACTERS.length())));
        }
        return sb.toString();
    }
 
    public AddReportPage() {
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_VehicleNo = new javax.swing.JTextField();
        txt_AddNic = new javax.swing.JTextField();
        cmb_ViolationType = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_Location = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_Description = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txt_Comments = new javax.swing.JTextArea();
        btn_SaveRpt = new javax.swing.JButton();
        btn_ClearRpt = new javax.swing.JButton();
        jSpinner1 = new javax.swing.JSpinner();
        btn_browse = new javax.swing.JButton();
        txt_AddLink = new javax.swing.JTextField();
        jLabelStatus = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_ReporterName = new javax.swing.JTextField();
        btn_back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Add Your Report");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(296, 296, 296)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Name");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("NIC");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Date/Time");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Violation Type");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Location");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Description");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Comments / Suggestions");

        cmb_ViolationType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_ViolationTypeActionPerformed(evt);
            }
        });

        txt_Location.setColumns(20);
        txt_Location.setRows(5);
        jScrollPane2.setViewportView(txt_Location);

        txt_Description.setColumns(20);
        txt_Description.setRows(5);
        jScrollPane1.setViewportView(txt_Description);

        txt_Comments.setColumns(20);
        txt_Comments.setRows(5);
        txt_Comments.setPreferredSize(new java.awt.Dimension(150, 84));
        jScrollPane3.setViewportView(txt_Comments);

        btn_SaveRpt.setBackground(new java.awt.Color(0, 204, 51));
        btn_SaveRpt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_SaveRpt.setForeground(new java.awt.Color(255, 255, 255));
        btn_SaveRpt.setText("Save");
        btn_SaveRpt.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_SaveRpt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SaveRptActionPerformed(evt);
            }
        });

        btn_ClearRpt.setBackground(new java.awt.Color(153, 153, 153));
        btn_ClearRpt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_ClearRpt.setForeground(new java.awt.Color(255, 255, 255));
        btn_ClearRpt.setText("Clear");
        btn_ClearRpt.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_ClearRpt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ClearRptActionPerformed(evt);
            }
        });

        jSpinner1.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), new java.util.Date(1723214040000L), new java.util.Date(), java.util.Calendar.HOUR));

        btn_browse.setBackground(new java.awt.Color(153, 153, 153));
        btn_browse.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_browse.setForeground(new java.awt.Color(255, 255, 255));
        btn_browse.setText("Browse");
        btn_browse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_browseActionPerformed(evt);
            }
        });

        txt_AddLink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_AddLinkActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Vehicle Number");

        txt_ReporterName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ReporterNameActionPerformed(evt);
            }
        });

        btn_back.setBackground(new java.awt.Color(153, 153, 153));
        btn_back.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_back.setForeground(new java.awt.Color(255, 255, 255));
        btn_back.setText("Home ");
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_VehicleNo, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(cmb_ViolationType, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_ReporterName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 141, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jSpinner1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(txt_AddNic, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txt_AddLink, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_browse, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(44, 44, 44))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jLabelStatus))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(btn_SaveRpt, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(91, 91, 91)
                        .addComponent(btn_ClearRpt, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79)
                        .addComponent(btn_back, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(112, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_ReporterName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmb_ViolationType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_VehicleNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_AddNic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_AddLink, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_browse, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(jLabelStatus)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_SaveRpt, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_ClearRpt)
                    .addComponent(btn_back, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(108, Short.MAX_VALUE))
        );

        cmb_ViolationType.setModel(new javax.swing.DefaultComboBoxModel<>(new ComboItem[] {
            new ComboItem("Speeding", "1"),
            new ComboItem("Running red lights or stop signs", "2"),
            new ComboItem("Improper overtaking", "3"),
            new ComboItem("Failure to yield", "4"),
            new ComboItem("Reckless driving", "5"),
            new ComboItem("Illegal turns or U-turns", "6"),
            new ComboItem("Not using turn signals", "7"),
            new ComboItem("Distracted driving", "8"),
            new ComboItem("Driving under the influence (DUI)", "9"),
            new ComboItem("Driving the wrong way", "10")
        }));
        ((JSpinner.DateEditor) jSpinner1.getEditor()).getFormat().applyPattern("dd MMMM yyyy");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_browseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_browseActionPerformed


      JFileChooser chooser = new JFileChooser();

    // Optional: restrict to audio/video files
    chooser.setFileFilter(new javax.swing.filechooser.FileFilter() {
        public boolean accept(File f) {
            if (f.isDirectory()) return true;
            String name = f.getName().toLowerCase();
            return name.endsWith(".mp3") || name.endsWith(".wav") || name.endsWith(".mp4") ||
                   name.endsWith(".avi") || name.endsWith(".mkv") || name.endsWith(".mov");
        }
        public String getDescription() {
            return "Audio/Video Files (*.mp3, *.mp4, etc.)";
        }
    });

    int result = chooser.showOpenDialog(this);
    if (result == JFileChooser.APPROVE_OPTION) {
        selectedFile = chooser.getSelectedFile();
        txt_AddLink.setText(selectedFile.getAbsolutePath()); // Optional: show the path
    }







    }//GEN-LAST:event_btn_browseActionPerformed

    private void btn_SaveRptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SaveRptActionPerformed
String ValidateMsg="";
 String ReporterName = txt_ReporterName.getText().trim();
 String AddNic = txt_AddNic.getText().trim();
String VehicleNo = txt_VehicleNo.getText().trim();
String Location = txt_Location.getText().trim();
 //String ReporterName = txt_ReporterName.getText().trim();
 //String ReporterName = txt_ReporterName.getText().trim();
        
        if (ReporterName.isEmpty()) {
             ValidateMsg="Please enter your name\n";
            }
        
         if (AddNic.isEmpty()) {
            ValidateMsg+="Please enter your NIC\n";
           }
        
         if (VehicleNo.isEmpty()) {
            ValidateMsg+="Please enter reporting Vehicle Number\n";
           }
         
         if (Location.isEmpty()) {
            ValidateMsg+="Please enter incident happened location\n";
           }
         
        if (ReporterName.isEmpty()||AddNic.isEmpty()||VehicleNo.isEmpty()||Location.isEmpty()) {
              JOptionPane.showMessageDialog(null, ValidateMsg);
            return;
        }
        
        if (selectedFile == null) {
        JOptionPane.showMessageDialog(this, "Please select a file first.");
        return;
    }
    
    
    
        

    // Set status
    jLabelStatus.setText("Uploading... Please wait");

    // Disable buttons to prevent multiple uploads
    btn_SaveRpt.setEnabled(false);
    btn_browse.setEnabled(false);

    // Run upload in background
    SwingWorker<Void, Void> worker = new SwingWorker<Void, Void>() {
        @Override
        protected Void doInBackground() throws Exception {
            uploadFileToServer(selectedFile);
           
         // Save to DB
           
              
              
            
            return null;
        }

        @Override
        protected void done() {
            try {
                get(); // Check if any exceptions occurred
                jLabelStatus.setText("Upload completed.");
            } catch (Exception ex) {
                jLabelStatus.setText("Upload failed.");
                JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage());
            }

            // Re-enable buttons
            btn_SaveRpt.setEnabled(true);
            btn_browse.setEnabled(true);
        }
    };

    worker.execute(); // Start the background task

        // TODO add your handling code here:
    }//GEN-LAST:event_btn_SaveRptActionPerformed

    private void cmb_ViolationTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_ViolationTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_ViolationTypeActionPerformed

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        // TODO add your handling code here:
        new HomePage().setVisible(true); 
   dispose();
    }//GEN-LAST:event_btn_backActionPerformed

    private void btn_ClearRptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ClearRptActionPerformed
txt_ReporterName.setText("");      
txt_Comments.setText("");
txt_AddNic.setText("");
txt_Description.setText("");
txt_Location.setText("");
txt_VehicleNo.setText("");
txt_AddLink.setText("");
    }//GEN-LAST:event_btn_ClearRptActionPerformed

    private void txt_ReporterNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ReporterNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ReporterNameActionPerformed

    private void txt_AddLinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_AddLinkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_AddLinkActionPerformed
    ////////////// start upload
 
    public void uploadFileToServer(File fileToUpload) {
    String serverURL = "https://eonepisode.com/trafficreporter/upload.php"; // Change to your actual URL

    try {
        String boundary = Long.toHexString(System.currentTimeMillis());
        String CRLF = "\r\n";
        URL url = new URL(serverURL);
        
        HttpURLConnection connection = (HttpURLConnection) url.openConnection();

        connection.setDoOutput(true);
        connection.setRequestMethod("POST");
        connection.setRequestProperty("Content-Type", "multipart/form-data; boundary=" + boundary);

        try (
            OutputStream output = connection.getOutputStream();
            PrintWriter writer = new PrintWriter(new OutputStreamWriter(output, "UTF-8"), true);
        ) {
            // Send file
            writer.append("--" + boundary).append(CRLF);
            
           String fileName = fileToUpload.getName();
String extension = "";

int i = fileName.lastIndexOf('.');
if (i > 0) {
    extension = fileName.substring(i + 1); // This gives "mp4", "jpg", etc.
}
long timestamp = System.currentTimeMillis();
String shortHash = generateShortHash(5);
String pre_name=timestamp+shortHash;

 String f_fileName =pre_name+"."+extension;
 
            //System.out.println(filename);
            
            
            writer.append("Content-Disposition: form-data; name=\"file\"; filename=\"" + f_fileName + "\"").append(CRLF);
            writer.append("Content-Type: " + HttpURLConnection.guessContentTypeFromName(f_fileName)).append(CRLF);
            writer.append(CRLF).flush();

            Files.copy(fileToUpload.toPath(), output);
            output.flush();

            writer.append(CRLF).flush();
            writer.append("--" + boundary + "--").append(CRLF).flush();
            String reporterName = txt_ReporterName.getText();
            
    String nic = txt_AddNic.getText();
    String vehicleNo = txt_VehicleNo.getText();
    String location = txt_Location.getText();
    String description = txt_Description.getText();
    String comments = txt_Comments.getText();
   
    
    
    ComboItem violationTypeselectedItem = (ComboItem) cmb_ViolationType.getSelectedItem();
    String violationTypeselectedItem_f="0";
if (violationTypeselectedItem != null) {
     violationTypeselectedItem_f = violationTypeselectedItem.getValue();
    
}

    java.util.Date date = (java.util.Date) jSpinner1.getValue();
    java.sql.Date sqlDate = new java.sql.Date(date.getTime());
    
             try (Connection con = DBConnection.CreateConnection()) {
                String sql = "INSERT INTO reports (name, nic, vehicle_number, violation_type, date_time, "
                        + "location, "
                        + "comments, description, video_path) VALUES ("
                        + "?,"
                        + " ?,"
                        + " ?,"
                        + " ?,"
                        + " ?,"
                        + " ?,"
                        + " ?,"
                        + " ?,"
                        + " ?)";
               
                try (PreparedStatement stmt = con.prepareStatement(sql)) {
                    stmt.setString(1, reporterName);
                    stmt.setString(2, nic);
                    stmt.setString(3, vehicleNo);
                    stmt.setString(4, violationTypeselectedItem_f);
                     stmt.setDate(5, sqlDate);
                    stmt.setString(6, location);
              stmt.setString(7, comments);
                    stmt.setString(8, description);
                   stmt.setString(9, f_fileName); //https://eonepisode.com/trafficreporter/uploads/1749794035306jE94a.mp4
                    stmt.executeUpdate();
                }
            }  
        }

        // Read response
        int responseCode = connection.getResponseCode();
        BufferedReader in = new BufferedReader(new InputStreamReader(connection.getInputStream()));
        String line;
        StringBuilder response = new StringBuilder();

        while ((line = in.readLine()) != null) {
            response.append(line).append("\n");
        }
        in.close();

        System.out.println("Server Response: " + response.toString());
        
        
    } catch (Exception e) {
        e.printStackTrace();
    }
}

    ///end
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        System.setProperty("awt.useSystemAAFontSettings", "on");
System.setProperty("swing.aatext", "true");
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddReportPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddReportPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddReportPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddReportPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddReportPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ClearRpt;
    private javax.swing.JButton btn_SaveRpt;
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_browse;
    private javax.swing.JComboBox<ComboItem> cmb_ViolationType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelStatus;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextField txt_AddLink;
    private javax.swing.JTextField txt_AddNic;
    private javax.swing.JTextArea txt_Comments;
    private javax.swing.JTextArea txt_Description;
    private javax.swing.JTextArea txt_Location;
    private javax.swing.JTextField txt_ReporterName;
    private javax.swing.JTextField txt_VehicleNo;
    // End of variables declaration//GEN-END:variables


}
